//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightScale.Presentation.Resources.Constants {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeightScale.Presentation.Resources.Constants.DialogMessages", typeof(DialogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the work order? Unsaved changes will be lost..
        /// </summary>
        internal static string ConfirmChangeWorkOrder {
            get {
                return ResourceManager.GetString("ConfirmChangeWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave? Unsaved data will be lost..
        /// </summary>
        internal static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work order is empty.
        /// </summary>
        internal static string EmptyWorkOrderWarning {
            get {
                return ResourceManager.GetString("EmptyWorkOrderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is in use.
        /// </summary>
        internal static string FileInUseWarning {
            get {
                return ResourceManager.GetString("FileInUseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot leave this operation right now..
        /// </summary>
        internal static string ForbiddenMessage {
            get {
                return ResourceManager.GetString("ForbiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied for the user..
        /// </summary>
        internal static string NoAccessForUser {
            get {
                return ResourceManager.GetString("NoAccessForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflow main PCB?.
        /// </summary>
        internal static string ReflowMainPcbWarning {
            get {
                return ResourceManager.GetString("ReflowMainPcbWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflow sensor PCB?.
        /// </summary>
        internal static string ReflowSensorPcbWarning {
            get {
                return ResourceManager.GetString("ReflowSensorPcbWarning", resourceCulture);
            }
        }
    }
}
